# Generated by Django 5.2.5 on 2025-12-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Id chat')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
        ),
    ]
