# Generated by Django 5.2.5 on 2025-12-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chattelegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattelegram',
            name='chat_id',
            field=models.CharField(blank=True, null=True, verbose_name='Id chat'),
        ),
    ]
