# Generated by Django 5.2.5 on 2025-12-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_chattelegram_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
